### ISSUE TITLE
Xdebug 3 and PHP 8.1 - not working

### ISSUE THREAD

**Issue by mattgrul** [wardenenv/warden#568] opened 2022-12-25 22:44 UTC
When running a brand new install on Magento 2 using the below conifg, xdebug fails to break.

ELASTICSEARCH_VERSION=7.17
MARIADB_VERSION=10.4
NODE_VERSION=16
COMPOSER_VERSION=2
PHP_VERSION=8.1
PHP_XDEBUG_3=1
RABBITMQ_VERSION=3.9
REDIS_VERSION=6.2
VARNISH_VERSION=7.0

When downgrading the PHP version to 7.4 then the breakpoints work correct without changing any other config settings in the IDE.

This makes me believe it's a 8.1 Image specific problem, debugging is out my remit but hopefully someone can shed some light.

```
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_SESSION'
[164] [Config] INFO: No shared secret: Activating
[164] [Step Debug] INFO: Checking for client discovery headers: 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] INFO: Checking header 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] WARN: Could not discover client host through HTTP headers, connecting to configured address/port: localhost:9003.
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', connect: Cannot assign requested address.
[164] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_TRACE'
[164] [Config] INFO: Trigger value for 'XDEBUG_TRACE' not found, so not activating
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_SESSION'
[164] [Config] INFO: No shared secret: Activating
[164] [Step Debug] INFO: Checking for client discovery headers: 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] INFO: Checking header 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] WARN: Could not discover client host through HTTP headers, connecting to configured address/port: localhost:9003.
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', connect: Cannot assign requested address.
[164] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_TRACE'
[164] [Config] INFO: Trigger value for 'XDEBUG_TRACE' not found, so not activating
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_SESSION'
[164] [Config] INFO: No shared secret: Activating
[164] [Step Debug] INFO: Checking for client discovery headers: 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] INFO: Checking header 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] WARN: Could not discover client host through HTTP headers, connecting to configured address/port: localhost:9003.
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', connect: Cannot assign requested address.
[164] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_TRACE'
[164] [Config] INFO: Trigger value for 'XDEBUG_TRACE' not found, so not activating
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_SESSION'
[164] [Config] INFO: No shared secret: Activating
[164] [Step Debug] INFO: Checking for client discovery headers: 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] INFO: Checking header 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] WARN: Could not discover client host through HTTP headers, connecting to configured address/port: localhost:9003.
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', connect: Cannot assign requested address.
[164] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_TRACE'
[164] [Config] INFO: Trigger value for 'XDEBUG_TRACE' not found, so not activating
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_SESSION'
[164] [Config] INFO: No shared secret: Activating
[164] [Step Debug] INFO: Checking for client discovery headers: 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] INFO: Checking header 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] WARN: Could not discover client host through HTTP headers, connecting to configured address/port: localhost:9003.
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', connect: Cannot assign requested address.
[164] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_TRACE'
[164] [Config] INFO: Trigger value for 'XDEBUG_TRACE' not found, so not activating
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_SESSION'
[164] [Config] INFO: No shared secret: Activating
[164] [Step Debug] INFO: Checking for client discovery headers: 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] INFO: Checking header 'HTTP_X_DEBUG_HOST'.
[164] [Step Debug] WARN: Could not discover client host through HTTP headers, connecting to configured address/port: localhost:9003.
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', poll success, but error: Operation now in progress (29).
[164] [Step Debug] WARN: Creating socket for 'localhost:9003', connect: Cannot assign requested address.
[164] [Step Debug] ERR: Could not connect to debugging client. Tried: localhost:9003 (fallback through xdebug.client_host/xdebug.client_port).
[164] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_TRACE'
[164] [Config] INFO: Trigger value for 'XDEBUG_TRACE' not found, so not activating
[164] Log closed at 2022-12-25 23:07:23.224448

```

**Comment by mattgrul** [comment] 2022-12-29 23:09
More detailed information can be found here [swiftotter/den/#177](https://github.com/swiftotter/den/issues/177)

**Comment by norgeindian** [comment] 2023-01-03 09:30
Maybe some additional finding from my side. Everything worked still fine in 2022 with PHP 8.1 and XDebug 3.
In the new year, I ran `warden env pull` and since then it is broken.
Can't really say when I did this the last time, but it seems to be related to the latest image.

**Comment by norgeindian** [comment] 2023-01-09 13:11
@navarr , is there anything we can help here? Or do you at least see some kind of workaround, which might work for the time being?
This is a huge issue for us, so it would be awesome, if we could find a way to fix it.

**Comment by sprankhub** [comment] 2023-01-09 13:45
@norgeindian, there seems to be a workaround roughly described in https://github.com/swiftotter/den/issues/177. I just did not get to check it in more detail yet.

**Comment by dgutman10** [comment] 2023-01-11 13:29
add this folder and xml file to the root of the project ".warden/warden-env.yml"

run docker inspect on the project network to know the network gateway and replace "172.21.0.1" with your gateway

 version: "3.5"
 services:
   nginx:
     environment:
       - XDEBUG_CONNECT_BACK_HOST=172.21.0.1

**Comment by navarr** [comment] 2023-01-11 13:55
Would someone running linux be able to tell me:

* The gateway IP (`docker inspect <proj>_default` and then under IPAM.Config.Gateway)
* The result of ` docker run -it --rm ubuntu:22.04 bash -c "apt-get update > /dev/null && apt-get install iproute2 -y > /dev/null && ip -4 route show default | cut -d' ' -f3"`
* The result of a page load with xdebug turned on, outputting: `$_SERVER['HTTP_X_FORWARDED_FOR']` and `$_SERVER['REMOTE_ADDR']`?

**Comment by davidalger** [comment] 2023-01-11 15:00
In case it's useful, the following should be able to be used to gather the gateway IP from within any running container without requiring additional packages:

```
awk '/32 host/ { if (i !~ /^127\./) print i } { i=$2 }' /proc/net/fib_trie | head -n1 | sed -E 's/\.[0-9]+$/\.1/'
```

Seemed interesting that this only affects PHP 8.1, but not PHP 7.4, so I took a look through Xdebug update notes and found this:

> Fixed bug [#1819](https://bugs.xdebug.org/bug_view_page.php?bug_id=00001819): Allow a list of headers in 'xdebug.client_discovery_header'

The last comment on that bug tracker reads:

> if someone upgraded to xdebug 3.2 and was using client_discovery_header you have to change it to:
>
> xdebug.client_discovery_header="YOUR_CURRENT_VALUE,HTTP_X_FORWARDED_FOR,REMOTE_ADDR"
>
> if you want the same behavior

Considering the [documentation](https://xdebug.org/docs/step_debug#client_discovery_header) on the feature hasn't changed to reflect this, could be a bug. Or it could be a miss on updating docs to reflect the BC break.

Since XDebug 3.2 dropped support for 7.4, the PHP 7.4 images are running XDebug 3.1 or 3.0 and thus unaffected by the  behavior change.

**Comment by navarr** [comment] 2023-01-11 15:22
Thank you @davidalger for your incredible insight.  

Since this seems to be intentional, I've opened a Documentation issue: https://bugs.xdebug.org/view.php?id=2154

For Warden, we're probably going to have to split XDebug config between versions as I don't see a way to update it and keep it backwards compatible 🤔

**Comment by norgeindian** [comment] 2023-01-13 10:51
Thanks a lot for the solutions here. That actually works fine for me and is totally perfect as a workaround for the time being.

**Comment by navarr** [comment] 2023-01-13 20:57
Theoretically, this will be fixed when https://github.com/wardenenv/images/actions/runs/3914748370 works.  I've confirmed XDebug still works on Windows after those changes, but I'll need someone on Linux to pull the images and test it out without a workaround once it's finished running

**Comment by navarr** [comment] 2023-01-14 04:08
Images are built and pushed

**Comment by sprankhub** [comment] 2023-01-14 13:04
I have tested this on Ubuntu 22.04 on a PHP 8.1 project:

* I disabled my workaround.
* I ran `warden env pull && warden env up`.
* I tested if XDebug works again.

Aaaannddd... It works again! Thanks to everyone involved fixing this!

**Comment by navarr** [comment] 2023-01-14 13:28
Thank you so much @sprankhub!

**Closed** 2023-01-14 13:28 UTC
Labels: bug
