### ISSUE TITLE
[Image] magento 2 error pull maria db

### ISSUE THREAD

**Issue by tfmlink1** [wardenenv/warden#627] opened 2023-03-22 00:03 UTC
### Version of Warden

1.3

### Operating System and Installation Method

ubuntu 22

### Image

Pulling db               ... error

### Describe the Bug

after several attempts when I run the warden env up there is always an error in the db container. 

### To Reproduce

wanden env up

**Comment by sprankhub** [comment] 2023-03-22 07:20
Sounds like a duplicate of https://github.com/wardenenv/warden/issues/622. Are you also using fish shell?

**Comment by therocketgroup** [comment] 2023-03-23 03:13
Docker Compose version v2.15.1

**Comment by bartekszymanski** [comment] 2023-03-23 15:42
@navarr check `environments/includes/db.base.yml` for the db image definition. In my opinion it should look like `image: ${WARDEN_IMAGE_REPOSITORY}/${DB_DISTRIBUTION:-mariadb}:${DB_DISTRIBUTION_VERSION:-10.4}`. After the changes, everything works as expected.

**Comment by navarr** [comment] 2023-03-23 17:16
@bartekszymanski It's not set that way so that it has backwards compatibility with `.env` files that define only `MARIADB_VERSION`

**Comment by jerrylopez** [comment] 2023-03-23 20:37
I had this same issue. I was able to resolve it by upgrading to`docker-compose` v2.

**Closed** 2024-01-03 16:41 UTC
Labels: bug, docker-images
