### ISSUE TITLE
invalid interpolation format for services.db.image

### ISSUE THREAD

**Issue by asantisan** [wardenenv/warden#689] opened 2023-08-26 22:09 UTC
### Version of Homebrew

Homebrew 4.1.6

### Operating System and Installation Method

Ubuntu 22.04.3 LTS

### Describe the Bug

when running `warden env up` or `warden env config` within the root project directory:

`invalid interpolation format for services.db.image: "${MARIADB_VERSION:-10.4". You may need to escape any $ with another $.`

Warden v0.14.1
Docker v24.0.5
Docker Compose version v2.2.3

### To Reproduce

`warden env up` or `warden env config` within the root project directory

### Expected Behavior

Create and start containers

**Comment by navarr** [comment] 2023-08-28 16:41
Duplicate of #627

**Closed by navarr** 2023-08-28 16:41 UTC
Labels: bug
